@baseUrl = http://localhost:3333

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Jeremias Mathias",
  "email": "geremias@example.com",
  "password": "123456"
}

# @name authentication
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "geremias@example.com",
  "password": "123456"
}